// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Status {

  /// <summary>Holder for reflection information generated from status.proto</summary>
  public static partial class StatusReflection {

    #region Descriptor
    /// <summary>File descriptor for status.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StatusReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzdGF0dXMucHJvdG8SBnN0YXR1cyJCChRTZXJ2ZXJTdGF0dXNSZXNwb25z",
            "ZRIqCgxTZXJ2ZXJTdGF0dXMYASABKA4yFC5zdGF0dXMuU2VydmVyU3RhdHVz",
            "KicKDFNlcnZlclN0YXR1cxIGCgJPSxAAEg8KC01BSU5URU5BTkNFEAFCEqoC",
            "D1Byb3RvYnVmLlN0YXR1c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.Status.ServerStatus), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protobuf.Status.ServerStatusResponse), global::Protobuf.Status.ServerStatusResponse.Parser, new[]{ "ServerStatus" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ServerStatus {
    [pbr::OriginalName("OK")] Ok = 0,
    [pbr::OriginalName("MAINTENANCE")] Maintenance = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ServerStatusResponse : pb::IMessage<ServerStatusResponse> {
    private static readonly pb::MessageParser<ServerStatusResponse> _parser = new pb::MessageParser<ServerStatusResponse>(() => new ServerStatusResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerStatusResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protobuf.Status.StatusReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerStatusResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerStatusResponse(ServerStatusResponse other) : this() {
      serverStatus_ = other.serverStatus_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerStatusResponse Clone() {
      return new ServerStatusResponse(this);
    }

    /// <summary>Field number for the "ServerStatus" field.</summary>
    public const int ServerStatusFieldNumber = 1;
    private global::Protobuf.Status.ServerStatus serverStatus_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Protobuf.Status.ServerStatus ServerStatus {
      get { return serverStatus_; }
      set {
        serverStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerStatusResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerStatusResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServerStatus != other.ServerStatus) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServerStatus != 0) hash ^= ServerStatus.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServerStatus != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ServerStatus);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServerStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ServerStatus);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerStatusResponse other) {
      if (other == null) {
        return;
      }
      if (other.ServerStatus != 0) {
        ServerStatus = other.ServerStatus;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            serverStatus_ = (global::Protobuf.Status.ServerStatus) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
